on:
  pull_request:
  push:
    branches:
      - main

name: Linters

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Run check
        uses: actions-rs/cargo@master
        with:
          command: check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Run fmt
        uses: actions-rs/cargo@master
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true
      - name: Run clippy
        uses: actions-rs/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output

  security_audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          override: true
      - name: Run audit
        uses: actions-rs/audit-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  super-linter:          
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          override: true
      - name: Run super-linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DISABLE_ERRORS: true
          VALIDATE_RUST_2015: false
          VALIDATE_RUST_2018: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}